"""Reports Table

Revision ID: d96a3945865d
Revises: 
Create Date: 2020-12-07 14:22:49.509226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd96a3945865d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('symbol', sa.String(length=128), nullable=False),
    sa.Column('overview', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('income_statement', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('balance_sheet', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cash_flow', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    # ### end Alembic commands ###
